server:
  port: 8080

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url: jdbc:mysql://localhost:3306/myapp_server?useSSL=false
    username: root
    password: 165831
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# springdoc-openapi ??
springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true

  group-configs: # ????
    - group: 'controller'
      paths-to-match: '/**'
      packages-to-scan: com.myapp.server.controller


# knife4j ??
knife4j:
  enable: true    # ??
  setting:
    language: zh_cn   # ??
    swagger-model-name: Entity  # ??????????
  basic:
    enable: true
    # swagger???
    username: user
    # swagger??
    password: 123456